apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartapp-api
  labels:
    app: smartapp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartapp-api
  template:
    metadata:
      labels:
        app: smartapp-api
    spec:
      containers:
        - name: smartapp-api
          image: shylendra2015/smartapp-api:latest
          imagePullPolicy: Always
          args: ["--spring.profiles.active=dev"]
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: smartapp-api-svc
spec:
  ports:
    - port: 80
      targetPort: 8082
      protocol: TCP
  selector:
    app: smartapp-api